version: 3

tasks:
  create_ns:
    cmds:
      - 'kubectl create namespace semaphore'
    desc: 'Creates app namespace'
  
  create_secret:
    cmds:
      - 'python3 gen_secret.py'
    desc: 'Creates Secret manifest'
  
  apply:
    cmds:
      - 'kubectl apply -f ./manifests -n semaphore'
    desc: 'Applies the manifests on namespace semaphore' 