apiVersion: v1
kind: ConfigMap

metadata:
  name: semaphore-cfg

data:
  SEMAPHORE_DB_USER: "semaphore"
  SEMAPHORE_DB_HOST: "postgres"
  SEMAPHORE_DB_PORT: "5432"
  SEMAPHORE_DB_DIALECT: "postgres"
  SEMAPHORE_DB: "semaphore"

  SEMAPHORE_ADMIN_NAME: "semaphore-admin"
  SEMAPHORE_ADMIN_EMAIL: "shevchenko.v87@wb.ru"
  SEMAPHORE_ADMIN: semaphore-admin

  SEMAPHORE_LDAP_ACTIVATED: 'no'