apiVersion: apps/v1
kind: Deployment

metadata:
  name: &appName semaphore
  namespace: semaphore
  labels:
    app: *appName
    version: &version v2.9.37

spec:
  replicas: 1

  # Выбираем поды для деплоя
  selector:
    matchLabels:
      app: *appName
      version: *version

  template:
    metadata:
      labels:
        app: *appName
        version: *version

    spec:
      # product=cicd:NoSchedule
      tolerations:
        - key: "product"
          operator: "Equal"
          value: "cicd"
          effect: "NoSchedule"

      volumes:
        - name: playbook_volume
          persistentVolumeClaim:
            claimName: semaphore

      containers:
        - name: semaphore
          imagePullPolicy: IfNotPresent
          image: semaphoreui/semaphore:v2.9.37

          envFrom:
            - secretRef:
                name: semaphore-cfg
            - configMapRef:
                name: semaphore-cfg
          env:
            - name: SEMAPHORE_PLAYBOOK_PATH
              value: "/opt/semaphore_data/"

          ports:
            - containerPort: 3000
              name: http

          readinessProbe:
            httpGet:
              port: 3000
              path: /ping
              scheme: HTTP

            initialDelaySeconds: 5
            periodSeconds: 3

          livenessProbe:
            httpGet:
              port: 3000
              path: /
              scheme: HTTP

            initialDelaySeconds: 10
            periodSeconds: 3

          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"

            requests:
              cpu: "200m"
              memory: "256Mi"

          volumeMounts:
            - mountPath: /opt/semaphore_data/
              name: playbook_volume