apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-storage