apiVersion: v1
kind: Service

metadata:
  name: semaphore
  labels:
    app: semaphore-test
    version: v2.9.37

spec:
  selector:
    app: semaphore-test
    version: v2.9.37

  ports:
    - protocol: TCP
      port: 3000
      targetPort: http